// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package buildkite

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetMetadata(ctx *pulumi.Context, opts ...pulumi.InvokeOption) (*GetMetadataResult, error) {
	var rv GetMetadataResult
	err := ctx.Invoke("buildkite:index/getMetadata:getMetadata", nil, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of values returned by getMetadata.
type GetMetadataResult struct {
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
	// A list of strings, each one an IP address (x.x.x.x) or CIDR address (x.x.x.x/32) that Buildkite may use to send webhooks and other external requests.
	WebhookIps []string `pulumi:"webhookIps"`
}
