// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

// API token with GraphQL access and `write_pipelines, read_pipelines` scopes
func GetApiToken(ctx *pulumi.Context) string {
	return config.Get(ctx, "buildkite:apiToken")
}

// The Buildkite organization ID
func GetOrganization(ctx *pulumi.Context) string {
	return config.Get(ctx, "buildkite:organization")
}
